sodu: required
services:
  - docker

before_install:
  - docker build -t trishten/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trishten/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  buket_name: "elasticbeanstalk-us-east-2-258445496998"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"